# Generated by Django 6.0.1 on 2026-04-13 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_aiquestiontemplate_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiinterviewsession',
            name='current_index',
            field=models.IntegerField(default=0),
        ),
    ]
