# Generated by Django 6.0.1 on 2026-04-13 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_aiinterviewsession_current_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianswer',
            name='ai_feedback',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='completeness_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='final_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='keyword_score',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='aianswer',
            name='relevance_score',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
