# Generated by Django 6.0.1 on 2026-04-27 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_subscriptionplan_paymenttransaction_billinghistory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=dict),
        ),
    ]
